import { motion } from 'framer-motion'
import { CircleDot, RotateCcw } from 'lucide-react'
import { formatNumber, getArcLength, getChordLength, getSectorArea, type CircleMode, type CircleState } from '../../logic/circulo'

interface Props { state: CircleState; mode: CircleMode; angle: number; onModeChange: (mode: CircleMode) => void }
const cx = 330; const cy = 215; const r = 155
const point = (deg: number) => { const a = ((deg - 90) * Math.PI) / 180; return { x: cx + r * Math.cos(a), y: cy + r * Math.sin(a) } }
const sectorPath = (deg: number) => { const s = point(0); const e = point(deg); return 'M ' + cx + ' ' + cy + ' L ' + s.x + ' ' + s.y + ' A ' + r + ' ' + r + ' 0 ' + (deg > 180 ? 1 : 0) + ' 1 ' + e.x + ' ' + e.y + ' Z' }
const arcPath = (startDeg: number, endDeg: number) => { const s = point(startDeg); const e = point(endDeg); return 'M ' + s.x + ' ' + s.y + ' A ' + r + ' ' + r + ' 0 ' + (endDeg - startDeg > 180 ? 1 : 0) + ' 1 ' + e.x + ' ' + e.y }

export default function CircleVisualization({ state, mode, angle, onModeChange }: Props) {
  const end = point(angle); const start = point(0)
  const chord = getChordLength(state.radius, angle); const arc = getArcLength(state.radius, angle); const sector = getSectorArea(state.radius, angle)
  const remainder = state.ratio - 3
  return (
    <div className="w-full">
      <div className="mb-2 flex flex-wrap items-center justify-between gap-2 px-1">
        <div><div className="flex items-center gap-2 text-sm font-bold text-slate-800"><CircleDot size={18} className="text-blue-700" />{mode === 'circunferencia' ? 'Experimento da circunferência' : 'Laboratório do círculo'}</div><p className="mt-0.5 text-xs text-slate-500">{mode === 'circunferencia' ? 'Veja o comprimento da borda virar uma linha.' : 'A geometria responde às suas escolhas.'}</p></div>
        <span className="rounded-full border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">r = {formatNumber(state.radius)} u</span>
      </div>
      <svg viewBox="0 0 900 540" role="img" aria-label="Visualização interativa do círculo" className="w-full">
        <defs><linearGradient id="circleFill" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stopColor="#dbeafe" /><stop offset="100%" stopColor="#f8fafc" /></linearGradient></defs>
        {mode !== 'circunferencia' && <motion.g initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }}>
          <circle cx={cx} cy={cy} r={r} fill="url(#circleFill)" stroke="#2563eb" strokeWidth="5" />
          <circle cx={cx} cy={cy} r={r + 10} fill="none" stroke="#dbeafe" strokeWidth="2" strokeDasharray="3 8" />
          {mode === 'medidas' && <><line x1={cx} y1={cy} x2={cx+r} y2={cy} stroke="#1d4ed8" strokeWidth="5" strokeLinecap="round"/><circle cx={cx} cy={cy} r="7" fill="#1d4ed8"/><text x={cx+r/2} y={cy-14} textAnchor="middle" className="fill-blue-800 text-[16px] font-black">r = {formatNumber(state.radius)} u</text><line x1={cx-r} y1={cy+50} x2={cx+r} y2={cy+50} stroke="#7c3aed" strokeWidth="4" strokeLinecap="round"/><text x={cx} y={cy+78} textAnchor="middle" className="fill-violet-800 text-[15px] font-black">D = {formatNumber(state.diameter)} u</text></>}
          {mode === 'angulos' && <><path d={sectorPath(angle)} fill="#bfdbfe" fillOpacity="0.72" stroke="#2563eb" strokeWidth="2"/><line x1={cx} y1={cy} x2={start.x} y2={start.y} stroke="#1d4ed8" strokeWidth="4"/><line x1={cx} y1={cy} x2={end.x} y2={end.y} stroke="#1d4ed8" strokeWidth="4"/><text x={cx+18} y={cy-18} className="fill-blue-900 text-[19px] font-black">{angle}°</text><text x={cx} y={cy+r+30} textAnchor="middle" className="fill-slate-600 text-[13px] font-semibold">arco = {formatNumber(arc)} u · corda = {formatNumber(chord)} u</text></>}
          {mode === 'area' && <><path d={sectorPath(angle)} fill="#60a5fa" fillOpacity="0.42" stroke="#2563eb" strokeWidth="2"/><text x={cx} y={cy+5} textAnchor="middle" className="fill-blue-900 text-[20px] font-black">{angle}°</text><text x={cx} y={cy+r+30} textAnchor="middle" className="fill-slate-600 text-[13px] font-semibold">setor = {formatNumber(sector)} u²</text></>}
          {mode === 'elementos' && <><line x1={cx} y1={cy} x2={cx+r} y2={cy} stroke="#1d4ed8" strokeWidth="4"/><line x1={cx-r} y1={cy} x2={cx+r} y2={cy} stroke="#7c3aed" strokeWidth="4"/><path d={arcPath(300,60)} fill="none" stroke="#0f766e" strokeWidth="8" strokeLinecap="round"/><line x1={cx-92} y1={cy+88} x2={cx+92} y2={cy+88} stroke="#ea580c" strokeWidth="5" strokeLinecap="round"/><circle cx={cx} cy={cy} r="7" fill="#1d4ed8"/><text x={cx+r/2} y={cy-13} textAnchor="middle" className="fill-blue-800 text-[15px] font-black">raio</text><text x={cx} y={cy+28} textAnchor="middle" className="fill-violet-800 text-[15px] font-black">diâmetro</text><text x={cx} y={cy-r-25} textAnchor="middle" className="fill-teal-700 text-[15px] font-black">arco</text><text x={cx} y={cy+116} textAnchor="middle" className="fill-orange-700 text-[15px] font-black">corda</text><text x={cx+14} y={cy-12} className="fill-slate-600 text-[13px] font-bold">centro</text></>}
        </motion.g>}
        {mode === 'circunferencia' && <><motion.g initial={{ opacity: 1 }} animate={{ opacity: 0.16 }} transition={{ duration: 0.7 }}><circle cx={cx} cy={cy} r={r} fill="#eff6ff" stroke="#2563eb" strokeWidth="5" /></motion.g><motion.circle cx={cx} cy={cy} r={r} fill="none" stroke="#2563eb" strokeWidth="8" strokeLinecap="round" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} transition={{ duration: 1.6 }} /><motion.circle r="10" fill="#1d4ed8" initial={{ cx: cx+r, cy }} animate={{ cx: [cx+r,cx,cx-r,cx,cx+r], cy: [cy,cy-r,cy,cy+r,cy] }} transition={{ duration: 1.6, ease: 'linear' }}/><motion.path d="M 70 430 C 190 390, 300 470, 420 430 S 660 390, 830 430" fill="none" stroke="#dbeafe" strokeWidth="24" strokeLinecap="round" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} transition={{ duration: 1.5, delay: 1.3 }} /><motion.path d="M 70 430 C 190 390, 300 470, 420 430 S 660 390, 830 430" fill="none" stroke="#2563eb" strokeWidth="14" strokeLinecap="round" initial={{ pathLength: 0 }} animate={{ pathLength: 1 }} transition={{ duration: 1.5, delay: 1.3 }}/>{[0,1,2].map(i => <g key={i}><line x1={70+i*253} y1="401" x2={70+i*253} y2="459" stroke="#1e40af" strokeWidth="2"/><text x={196.5+i*253} y="387" textAnchor="middle" className="fill-blue-800 text-[16px] font-black">{i+1}D</text></g>)}<text x="786" y="387" textAnchor="middle" className="fill-blue-700 text-[13px] font-black">+{formatNumber(remainder,5)}D</text><text x="450" y="505" textAnchor="middle" className="fill-slate-700 text-[15px] font-black">C ÷ D = {formatNumber(state.ratio,5)} ≈ π</text></>}
        {mode !== 'circunferencia' && <text x="450" y="510" textAnchor="middle" className="fill-slate-500 text-[13px] font-semibold">{mode === 'elementos' ? 'Cada elemento tem uma função diferente na geometria do círculo.' : mode === 'area' ? 'A área do setor depende diretamente do ângulo central.' : mode === 'angulos' ? 'Mova o ângulo e observe arco e corda mudarem juntos.' : 'Altere o raio e observe todas as medidas acompanharem a mudança.'}</text>}
      </svg>
      {mode === 'circunferencia' && <button type="button" onClick={() => onModeChange('medidas')} className="mt-2 inline-flex min-h-[44px] items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 hover:bg-slate-50"><RotateCcw size={15}/> Voltar ao laboratório</button>}
    </div>
  )
}